/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AuthenticatedPlanoAcaoRouteImport } from './routes/_authenticated/plano-acao'
import { Route as AuthenticatedOrientadoraRouteImport } from './routes/_authenticated/orientadora'
import { Route as AuthenticatedOnboardingRouteImport } from './routes/_authenticated/onboarding'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCheckinRouteImport } from './routes/_authenticated/checkin'
import { Route as AuthenticatedAutorresponsabilidadeRouteImport } from './routes/_authenticated/autorresponsabilidade'
import { Route as AuthenticatedAutoavaliacaoRouteImport } from './routes/_authenticated/autoavaliacao'
import { Route as AuthenticatedAcoesRouteImport } from './routes/_authenticated/acoes'
import { Route as AuthenticatedPlanoAcaoPillarIdRouteImport } from './routes/_authenticated/plano-acao_.$pillarId'
import { Route as AuthenticatedPilarIdRouteImport } from './routes/_authenticated/pilar.$id'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPlanoAcaoRoute = AuthenticatedPlanoAcaoRouteImport.update({
  id: '/plano-acao',
  path: '/plano-acao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOrientadoraRoute =
  AuthenticatedOrientadoraRouteImport.update({
    id: '/orientadora',
    path: '/orientadora',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOnboardingRoute = AuthenticatedOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckinRoute = AuthenticatedCheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAutorresponsabilidadeRoute =
  AuthenticatedAutorresponsabilidadeRouteImport.update({
    id: '/autorresponsabilidade',
    path: '/autorresponsabilidade',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAutoavaliacaoRoute =
  AuthenticatedAutoavaliacaoRouteImport.update({
    id: '/autoavaliacao',
    path: '/autoavaliacao',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAcoesRoute = AuthenticatedAcoesRouteImport.update({
  id: '/acoes',
  path: '/acoes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPlanoAcaoPillarIdRoute =
  AuthenticatedPlanoAcaoPillarIdRouteImport.update({
    id: '/plano-acao_/$pillarId',
    path: '/plano-acao/$pillarId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPilarIdRoute = AuthenticatedPilarIdRouteImport.update({
  id: '/pilar/$id',
  path: '/pilar/$id',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/autoavaliacao': typeof AuthenticatedAutoavaliacaoRoute
  '/autorresponsabilidade': typeof AuthenticatedAutorresponsabilidadeRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orientadora': typeof AuthenticatedOrientadoraRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/api/chat': typeof ApiChatRoute
  '/pilar/$id': typeof AuthenticatedPilarIdRoute
  '/plano-acao/$pillarId': typeof AuthenticatedPlanoAcaoPillarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/acoes': typeof AuthenticatedAcoesRoute
  '/autoavaliacao': typeof AuthenticatedAutoavaliacaoRoute
  '/autorresponsabilidade': typeof AuthenticatedAutorresponsabilidadeRoute
  '/checkin': typeof AuthenticatedCheckinRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/onboarding': typeof AuthenticatedOnboardingRoute
  '/orientadora': typeof AuthenticatedOrientadoraRoute
  '/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/api/chat': typeof ApiChatRoute
  '/pilar/$id': typeof AuthenticatedPilarIdRoute
  '/plano-acao/$pillarId': typeof AuthenticatedPlanoAcaoPillarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/acoes': typeof AuthenticatedAcoesRoute
  '/_authenticated/autoavaliacao': typeof AuthenticatedAutoavaliacaoRoute
  '/_authenticated/autorresponsabilidade': typeof AuthenticatedAutorresponsabilidadeRoute
  '/_authenticated/checkin': typeof AuthenticatedCheckinRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/onboarding': typeof AuthenticatedOnboardingRoute
  '/_authenticated/orientadora': typeof AuthenticatedOrientadoraRoute
  '/_authenticated/plano-acao': typeof AuthenticatedPlanoAcaoRoute
  '/api/chat': typeof ApiChatRoute
  '/_authenticated/pilar/$id': typeof AuthenticatedPilarIdRoute
  '/_authenticated/plano-acao_/$pillarId': typeof AuthenticatedPlanoAcaoPillarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/acoes'
    | '/autoavaliacao'
    | '/autorresponsabilidade'
    | '/checkin'
    | '/dashboard'
    | '/onboarding'
    | '/orientadora'
    | '/plano-acao'
    | '/api/chat'
    | '/pilar/$id'
    | '/plano-acao/$pillarId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/acoes'
    | '/autoavaliacao'
    | '/autorresponsabilidade'
    | '/checkin'
    | '/dashboard'
    | '/onboarding'
    | '/orientadora'
    | '/plano-acao'
    | '/api/chat'
    | '/pilar/$id'
    | '/plano-acao/$pillarId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/acoes'
    | '/_authenticated/autoavaliacao'
    | '/_authenticated/autorresponsabilidade'
    | '/_authenticated/checkin'
    | '/_authenticated/dashboard'
    | '/_authenticated/onboarding'
    | '/_authenticated/orientadora'
    | '/_authenticated/plano-acao'
    | '/api/chat'
    | '/_authenticated/pilar/$id'
    | '/_authenticated/plano-acao_/$pillarId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/plano-acao': {
      id: '/_authenticated/plano-acao'
      path: '/plano-acao'
      fullPath: '/plano-acao'
      preLoaderRoute: typeof AuthenticatedPlanoAcaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/orientadora': {
      id: '/_authenticated/orientadora'
      path: '/orientadora'
      fullPath: '/orientadora'
      preLoaderRoute: typeof AuthenticatedOrientadoraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/onboarding': {
      id: '/_authenticated/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthenticatedOnboardingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkin': {
      id: '/_authenticated/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof AuthenticatedCheckinRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autorresponsabilidade': {
      id: '/_authenticated/autorresponsabilidade'
      path: '/autorresponsabilidade'
      fullPath: '/autorresponsabilidade'
      preLoaderRoute: typeof AuthenticatedAutorresponsabilidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/autoavaliacao': {
      id: '/_authenticated/autoavaliacao'
      path: '/autoavaliacao'
      fullPath: '/autoavaliacao'
      preLoaderRoute: typeof AuthenticatedAutoavaliacaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/acoes': {
      id: '/_authenticated/acoes'
      path: '/acoes'
      fullPath: '/acoes'
      preLoaderRoute: typeof AuthenticatedAcoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/plano-acao_/$pillarId': {
      id: '/_authenticated/plano-acao_/$pillarId'
      path: '/plano-acao/$pillarId'
      fullPath: '/plano-acao/$pillarId'
      preLoaderRoute: typeof AuthenticatedPlanoAcaoPillarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pilar/$id': {
      id: '/_authenticated/pilar/$id'
      path: '/pilar/$id'
      fullPath: '/pilar/$id'
      preLoaderRoute: typeof AuthenticatedPilarIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAcoesRoute: typeof AuthenticatedAcoesRoute
  AuthenticatedAutoavaliacaoRoute: typeof AuthenticatedAutoavaliacaoRoute
  AuthenticatedAutorresponsabilidadeRoute: typeof AuthenticatedAutorresponsabilidadeRoute
  AuthenticatedCheckinRoute: typeof AuthenticatedCheckinRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedOnboardingRoute: typeof AuthenticatedOnboardingRoute
  AuthenticatedOrientadoraRoute: typeof AuthenticatedOrientadoraRoute
  AuthenticatedPlanoAcaoRoute: typeof AuthenticatedPlanoAcaoRoute
  AuthenticatedPilarIdRoute: typeof AuthenticatedPilarIdRoute
  AuthenticatedPlanoAcaoPillarIdRoute: typeof AuthenticatedPlanoAcaoPillarIdRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAcoesRoute: AuthenticatedAcoesRoute,
  AuthenticatedAutoavaliacaoRoute: AuthenticatedAutoavaliacaoRoute,
  AuthenticatedAutorresponsabilidadeRoute:
    AuthenticatedAutorresponsabilidadeRoute,
  AuthenticatedCheckinRoute: AuthenticatedCheckinRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedOnboardingRoute: AuthenticatedOnboardingRoute,
  AuthenticatedOrientadoraRoute: AuthenticatedOrientadoraRoute,
  AuthenticatedPlanoAcaoRoute: AuthenticatedPlanoAcaoRoute,
  AuthenticatedPilarIdRoute: AuthenticatedPilarIdRoute,
  AuthenticatedPlanoAcaoPillarIdRoute: AuthenticatedPlanoAcaoPillarIdRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
